services:
  postgresdb:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: clean
      POSTGRES_PASSWORD: arch123!
      POSTGRES_DB: clean-arch-postgres-db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: